module.exports = [
  {
    "rut_usuario": null,
    "id_actividad": 3,
    "temp_min": 10.0,
    "temp_max": 28.0,
    "viento_max": 20.0,
    "sense_min": 30.0,
    "sense_max": 70.0,
    "visibilidad": 5.0,
    "max_precipitaciones": 1.0,
    "alertas": [],
    "recomendaciones": [],
    "climas": []
  },
  {
    "rut_usuario": null,
    "id_actividad": 4,
    "temp_min": 10.0,
    "temp_max": 28.0,
    "viento_max": 20.0,
    "sense_min": 30.0,
    "sense_max": 70.0,
    "visibilidad": 5.0,
    "max_precipitaciones": 1.0,
    "alertas": [],
    "recomendaciones": [],
    "climas": []
  },
  {
    "rut_usuario": null,
    "id_actividad": 5,
    "temp_min": 10.0,
    "temp_max": 28.0,
    "viento_max": 20.0,
    "sense_min": 30.0,
    "sense_max": 70.0,
    "visibilidad": 5.0,
    "max_precipitaciones": 1.0,
    "alertas": [],
    "recomendaciones": [],
    "climas": []
  },
  {
    "rut_usuario": null,
    "id_actividad": 6,
    "temp_min": 10.0,
    "temp_max": 28.0,
    "viento_max": 20.0,
    "sense_min": 30.0,
    "sense_max": 70.0,
    "visibilidad": 5.0,
    "max_precipitaciones": 1.0,
    "alertas": [],
    "recomendaciones": [],
    "climas": []
  },
  {
    "rut_usuario": null,
    "id_actividad": 7,
    "temp_min": 10.0,
    "temp_max": 28.0,
    "viento_max": 20.0,
    "sense_min": 30.0,
    "sense_max": 70.0,
    "visibilidad": 5.0,
    "max_precipitaciones": 1.0,
    "alertas": [],
    "recomendaciones": [],
    "climas": []
  },
  {
    "rut_usuario": null,
    "id_actividad": 8,
    "temp_min": 10.0,
    "temp_max": 28.0,
    "viento_max": 20.0,
    "sense_min": 30.0,
    "sense_max": 70.0,
    "visibilidad": 5.0,
    "max_precipitaciones": 1.0,
    "alertas": [],
    "recomendaciones": [],
    "climas": []
  },
  {
    "rut_usuario": null,
    "id_actividad": 9,
    "temp_min": 10.0,
    "temp_max": 28.0,
    "viento_max": 20.0,
    "sense_min": 30.0,
    "sense_max": 70.0,
    "visibilidad": 5.0,
    "max_precipitaciones": 1.0,
    "alertas": [],
    "recomendaciones": [],
    "climas": []
  },
  {
    "rut_usuario": null,
    "id_actividad": 10,
    "temp_min": 10.0,
    "temp_max": 28.0,
    "viento_max": 20.0,
    "sense_min": 30.0,
    "sense_max": 70.0,
    "visibilidad": 5.0,
    "max_precipitaciones": 1.0,
    "alertas": [],
    "recomendaciones": [],
    "climas": []
  },
  {
    "rut_usuario": null,
    "id_actividad": 11,
    "temp_min": 10.0,
    "temp_max": 28.0,
    "viento_max": 20.0,
    "sense_min": 30.0,
    "sense_max": 70.0,
    "visibilidad": 5.0,
    "max_precipitaciones": 1.0,
    "alertas": [],
    "recomendaciones": [],
    "climas": []
  },
  {
    "rut_usuario": null,
    "id_actividad": 12,
    "temp_min": 10.0,
    "temp_max": 28.0,
    "viento_max": 20.0,
    "sense_min": 30.0,
    "sense_max": 70.0,
    "visibilidad": 5.0,
    "max_precipitaciones": 1.0,
    "alertas": [],
    "recomendaciones": [],
    "climas": []
  },
  {
    "rut_usuario": null,
    "id_actividad": 13,
    "temp_min": 10.0,
    "temp_max": 28.0,
    "viento_max": 20.0,
    "sense_min": 30.0,
    "sense_max": 70.0,
    "visibilidad": 5.0,
    "max_precipitaciones": 1.0,
    "alertas": [],
    "recomendaciones": [],
    "climas": []
  },
  {
    "rut_usuario": null,
    "id_actividad": 14,
    "temp_min": 10.0,
    "temp_max": 28.0,
    "viento_max": 20.0,
    "sense_min": 30.0,
    "sense_max": 70.0,
    "visibilidad": 5.0,
    "max_precipitaciones": 1.0,
    "alertas": [],
    "recomendaciones": [],
    "climas": []
  },
  {
    "rut_usuario": null,
    "id_actividad": 15,
    "temp_min": 10.0,
    "temp_max": 28.0,
    "viento_max": 20.0,
    "sense_min": 30.0,
    "sense_max": 70.0,
    "visibilidad": 5.0,
    "max_precipitaciones": 1.0,
    "alertas": [],
    "recomendaciones": [],
    "climas": []
  },
  {
    "rut_usuario": null,
    "id_actividad": 16,
    "temp_min": 10.0,
    "temp_max": 28.0,
    "viento_max": 20.0,
    "sense_min": 30.0,
    "sense_max": 70.0,
    "visibilidad": 5.0,
    "max_precipitaciones": 1.0,
    "alertas": [],
    "recomendaciones": [],
    "climas": []
  },
  {
    "rut_usuario": null,
    "id_actividad": 17,
    "temp_min": 10.0,
    "temp_max": 28.0,
    "viento_max": 20.0,
    "sense_min": 30.0,
    "sense_max": 70.0,
    "visibilidad": 5.0,
    "max_precipitaciones": 1.0,
    "alertas": [],
    "recomendaciones": [],
    "climas": []
  },
  {
    "rut_usuario": null,
    "id_actividad": 18,
    "temp_min": 10.0,
    "temp_max": 28.0,
    "viento_max": 20.0,
    "sense_min": 30.0,
    "sense_max": 70.0,
    "visibilidad": 5.0,
    "max_precipitaciones": 1.0,
    "alertas": [],
    "recomendaciones": [],
    "climas": []
  },
  {
    "rut_usuario": null,
    "id_actividad": 19,
    "temp_min": 10.0,
    "temp_max": 28.0,
    "viento_max": 20.0,
    "sense_min": 30.0,
    "sense_max": 70.0,
    "visibilidad": 5.0,
    "max_precipitaciones": 1.0,
    "alertas": [],
    "recomendaciones": [],
    "climas": []
  },
  {
    "rut_usuario": null,
    "id_actividad": 20,
    "temp_min": 15.0,
    "temp_max": 25.0,
    "viento_max": 100.0,
    "sense_min": 30.0,
    "sense_max": 70.0,
    "visibilidad": 0.0,
    "max_precipitaciones": 999.0,
    "alertas": [],
    "recomendaciones": [],
    "climas": []
  },
  {
    "rut_usuario": null,
    "id_actividad": 21,
    "temp_min": 15.0,
    "temp_max": 25.0,
    "viento_max": 100.0,
    "sense_min": 30.0,
    "sense_max": 70.0,
    "visibilidad": 0.0,
    "max_precipitaciones": 999.0,
    "alertas": [],
    "recomendaciones": [],
    "climas": []
  },
  {
    "rut_usuario": null,
    "id_actividad": 22,
    "temp_min": 15.0,
    "temp_max": 25.0,
    "viento_max": 100.0,
    "sense_min": 30.0,
    "sense_max": 70.0,
    "visibilidad": 0.0,
    "max_precipitaciones": 999.0,
    "alertas": [],
    "recomendaciones": [],
    "climas": []
  },
  {
    "rut_usuario": null,
    "id_actividad": 23,
    "temp_min": 15.0,
    "temp_max": 25.0,
    "viento_max": 100.0,
    "sense_min": 30.0,
    "sense_max": 70.0,
    "visibilidad": 0.0,
    "max_precipitaciones": 999.0,
    "alertas": [],
    "recomendaciones": [],
    "climas": []
  },
  {
    "rut_usuario": null,
    "id_actividad": 24,
    "temp_min": 15.0,
    "temp_max": 25.0,
    "viento_max": 100.0,
    "sense_min": 30.0,
    "sense_max": 70.0,
    "visibilidad": 0.0,
    "max_precipitaciones": 999.0,
    "alertas": [],
    "recomendaciones": [],
    "climas": []
  },
  {
    "rut_usuario": null,
    "id_actividad": 25,
    "temp_min": 15.0,
    "temp_max": 25.0,
    "viento_max": 100.0,
    "sense_min": 30.0,
    "sense_max": 70.0,
    "visibilidad": 0.0,
    "max_precipitaciones": 999.0,
    "alertas": [],
    "recomendaciones": [],
    "climas": []
  },
  {
    "rut_usuario": null,
    "id_actividad": 26,
    "temp_min": 15.0,
    "temp_max": 25.0,
    "viento_max": 100.0,
    "sense_min": 30.0,
    "sense_max": 70.0,
    "visibilidad": 0.0,
    "max_precipitaciones": 999.0,
    "alertas": [],
    "recomendaciones": [],
    "climas": []
  }
];